version: '3.8'

networks:
  default:
    name: ${DIREWOLF20_MINECRAFT_NETWORK:-games}

services:
  minecraft-direwolf20:
    image: itzg/minecraft-server:${DIREWOLF20_MINECRAFT_VERSION:-latest}
    container_name: ${DIREWOLF20_MINECRAFT_CONTAINER_NAME:-minecraft_direwolf20}
    hostname: ${DIREWOLF20_MINECRAFT_HOSTNAME:-minecraft_direwolf20}
    restart: ${DIREWOLF20_MINECRAFT_RESTART_POLICY:-unless-stopped}
    environment:
      - EULA=true
      - ENABLE_RCON=${DIREWOLF20_MINECRAFT_ENABLE_RCON:-true}
      - TYPE=${DIREWOLF20_MINECRAFT_TYPE:-FTBA}
      - FTB_MODPACK_ID=101
      - VIEW_DISTANCE=${DIREWOLF20_MINECRAFT_VIEW_DISTANCE:-10}
      - MEMORY=${DIREWOLF20_MINECRAFT_MEMORY:-4G}
      - INIT_MEMORY=8G
      - MAX_MEMORY=12G
      - USE_AIKAR_FLAGS=true
      - USE_LARGE_PAGES=true
      - CONSOLE=${DIREWOLF20_MINECRAFT_CONSOLE:-false}
    ports:
      - ${DIREWOLF20_MINECRAFT_PORT:-25565}:25565
    volumes:
      - ./etc/games/${DIREWOLF20_MINECRAFT_HOSTNAME:-minecraft_direwolf20}:/data
    labels:
      - joyride.host.name=${MINECRAFT_HOSTNAME:-minecraft_direwolf20}.${HOST_DOMAIN}
      - traefik.enable=false
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true
