version: '3'

networks:
  default:
    name: traefik
    
# https://github.com/ich777/docker-mindustry

services:
  mindustry:
    image: ich777/mindustry-server
    container_name: mindustry
    restart: unless-stopped
    environment:
      - SRV_NAME="MindustryServer"
      - UID=${PUID:-1000}
      - GID=${PGID:-1000}
    volumes:
      - ./etc/mindustry:/config
    labels:
      - joyride.host.name=mindustry.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.mindustry.entrypoints=websecure
      - traefik.http.routers.mindustry.rule=Host(`mindustry.${HOST_DOMAIN}`)
      - traefik.http.services.mindustry.loadbalancer.server.port=8096
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true