version: '3.8'
# https://hub.docker.com/r/itzg/minecraft-server
services:
  minecraft-paper:
    image: itzg/minecraft-server
    container_name: minecraft-paper
    restart: unless-stopped
    environment:
      EULA: "true"
      ENABLE_RCON: "true"
      TYPE: PAPER
      VIEW_DISTANCE: 10
      MEMORY: 2G
      CONSOLE: "false"
      VANILLATWEAKS_SHARECODE: jjOJob,o85sA9,lJvdCt
    ports:
      - 25565:25565
    volumes:
      - ./data:/data
