version: '3'

# https://github.com/willfarrell/docker-autoheal

services:  
  autoheal:
    image: willfarrell/autoheal:${AUTOHEAL_DOCKER_TAG:-latest}
    container_name: ${AUTOHEAL_CONTAINER_NAME:-autoheal}
    restart: unless-stopped
    environment: 
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=false 

