version: '3'

networks:
  default:
    name: traefik
    
# https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/
# https://hub.docker.com/r/cloudflare/cloudflared
# https://github.com/cloudflare/cloudflared


services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    volumes:
      - ./etc/cloudflared:/cloudflared
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    command: tunnel run --token ${CLOUDFLARED_TOKEN}
    #- --no-autoupdate
    #- --hello-world
    labels:
      - traefik.enable=false
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true