version: '3'

networks:
  default:
    name: traefik
    
https://github.com/coder/code-server
https://github.com/linuxserver/docker-code-server
https://docs.linuxserver.io/images/docker-code-server

services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    restart: unless-stopped
    volumes:
      - ./etc/code-server:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - PROXY_DOMAIN=code-server.${HOST_DOMAIN}
      #- SUDO_PASSWORD=password
    labels:
      - joyride.host.name=code-server.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.code-server.entrypoints=websecure
      - traefik.http.routers.code-server.rule=Host(`code-server.${HOST_DOMAIN}`)
      - traefik.http.services.code-server.loadbalancer.server.port=8443
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true