version: '3'

networks:
  default:
    name: traefik
    
# https://github.com/cocktailpeanut/dalai
# This file does requiere it's own setup and image as there is no image out there, it has to be build localy
# https://www.youtube.com/watch?v=PyZPyqQqkLE here for reference

services:
  dalai:
    image: dalai-dalai:${DALAI_DOCKER_TAG:-latest}
    container_name: ${DALAI_CONTAINER_NAME:-dalai} 
    restart: ${DALAI_RESTART:-unless-stopped}
    volumes:
      - ./etc/dalai:/root/dalai/ # <==== this probably needs changed 
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=${DALAI_CONTAINER_NAME:-dalai}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.dalai.entrypoints=websecure
      - traefik.http.routers.dalai.rule=Host(`${DALAI_CONTAINER_NAME:-dalai}.${HOST_DOMAIN}`)
      #- traefik.http.services.dalai.loadbalancer.server.scheme=https # enable if the service wants to connect over https
      - traefik.http.services.dalai.loadbalancer.server.port=3000
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${DALAI_FLAME_NAME:-dalai} 
      - flame.url=https://${DALAI_CONTAINER_NAME:-dalai}.${HOST_DOMAIN}
      - flame.icon=${DALAI_FLAME_ICON:-docker} # optional, default is "docker"