version: '3'

networks:
  default:
    name: traefik

# https://github.com/linuxserver/Heimdall

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    restart: unless-stopped
    volumes:
      - ./etc/heimdall:/config
    labels:
      - joyride.host.name=heimdall.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.heimdall.entrypoints=websecure
      - traefik.http.routers.heimdall.rule=Host(`heimdall.${HOST_DOMAIN}`)
      - traefik.http.routers.heimdall.tls=true
      - traefik.http.routers.heimdall.service=heimdall
      - traefik.http.services.heimdall.loadbalancer.server.port=80
