version: '3'

networks:
  default:
    name: traefik


services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    volumes:
      - ./etc/heimdall:/config
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: 
      - .env
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.heimdall.entrypoints=websecure
      - traefik.http.routers.heimdall.rule=Host(`heimdall.${HOST_DOMAIN}`)
      - traefik.http.routers.heimdall.tls=true
      - traefik.http.routers.heimdall.service=heimdall
      - traefik.http.services.heimdall.loadbalancer.server.port=80
