version: '3'

networks:
  default:
    name: traefik
    
# https://hub.docker.com/r/b4bz/homer

services:
  homer:
    image: b4bz/homer:latest
    container_name: homer
    restart: unless-stopped
    volumes:
      - ./etc/homer/assets/:/www/assets
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=homer.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.homer.entrypoints=websecure
      - traefik.http.routers.homer.rule=Host(`homer.${HOST_DOMAIN}`)
      - traefik.http.services.homer.loadbalancer.server.port=8080
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true