version: "3"
networks:
  default:
    name: traefik
  loki:
    name: loki

services:
  loki:
    container_name: loki
    image: grafana/loki:latest
    volumes:
      - ./etc/loki:/etc/loki
    ports:
      - 3100:3100
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=false

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
      - ./etc/promtail:/etc/promtail
    # ports:
    #   - 1514:1514 # this is only needed if you are going to send syslogs
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=false

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    user: ${PUID:-1000}
    ports:
      - 3000:3000
    networks:
      - default
      - loki
    env_file:
      - .env
    volumes:
      - ./etc/grafana:/var/lib/grafana
    labels:
      - joyride.host.name=logs.ilude.com
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`logs.ilude.com`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.services.grafana.loadbalancer.server.scheme=http
      - traefik.http.services.grafana.loadbalancer.server.port=3000