version: "3"
networks:
  default:
    name: traefik
  loki:
    name: loki

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    volumes:
      - ./etc/loki:/etc/loki
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=false

  logspout:
    image: gliderlabs/logspout
    container_name: logspout
    restart: unless-stopped
    command: syslog+tcp://promtail:1514
    networks:
      - loki
    depends_on:
      - promtail
    environment:
      - SYSLOG_HOSTNAME={{.ContainerName}}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=false

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: unless-stopped
    volumes:
      - /var/log:/var/log
      - ./etc/promtail:/etc/promtail
    # this is only needed if you are going to send syslogs
    # from an external source
    # ports:
    #   - 1514:1514 
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=false

  