version: '3'

networks:
  default:
    name: traefik
    
# https://github.com/mailhog/MailHog
 
services:
  mailhog:
    image: mailhog/mailhog:${MAILHOG_DOCKER_TAG:-latest}
    container_name: ${MAILHOG_CONTAINER_NAME:-mailhog} 
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MH_HOSTNAME=${MAILHOG_CONTAINER_NAME:-mailhog}.${HOST_DOMAIN}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      # - MH_OUTGOING_SMTP={'server name': {'name': 'Mailhog','host': 'postfix.${HOST_DOMAIN}','port': '25','email': 'noreply@${HOST_DOMAIN}' } }
      # - MH_MAILDIR_PATH=/storage 
      # - MH_STORAGE=maildir 
    labels:
      - joyride.host.name=${MAILHOG_CONTAINER_NAME:-mailhog}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.mailhog.entrypoints=websecure
      - traefik.http.routers.mailhog.rule=Host(`${MAILHOG_CONTAINER_NAME:-mailhog}.${HOST_DOMAIN}`)
      - traefik.http.services.mailhog.loadbalancer.server.port=8025
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true