version: '3'

networks:
  default:
    name: traefik
    
# <================= add links to documentation here =================>

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - ./etc/mariadb:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 33306:3306
    labels:
      - joyride.host.name=mariadb.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.mariadb.entrypoints=websecure
      - traefik.http.routers.mariadb.rule=Host(`mariadb.${HOST_DOMAIN}`)
      - traefik.http.services.mariadb.loadbalancer.server.port=8096
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true