version: '3'
networks:
  default:
    name: traefik

# https://hay-kot.github.io/mealie/documentation/getting-started/install/

services:
  mealie-postgres:
    container_name: mealie-postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD='mealie'
      - POSTGRES_USER='mealie'
    ports:
      - 5432:5432
    labels:
      - traefik.enable=false
      - com.centurylinklabs.watchtower.enable=false
      - autoheal=true

  mealie:
    image: hkotel/mealie:${MEALIE_DOCKER_TAG:-latest}
    container_name: ${MEALIE_CONTAINER_NAME:-mealie}
    restart: ${MEALIE_RESTART:-unless-stopped}
    depends_on: 
      - mealie-postgres
    volumes:
      - ./etc/mealie:/config # <==== this probably needs changed
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}

      # Database Settings
      
      - DB_ENGINE=postgres # Optional: 'sqlite', 'postgres'
      - POSTGRES_USER='mealie'
      - POSTGRES_PASSWORD='mealie'
      - POSTGRES_SERVER=mealie-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB='mealie'

      # Default Recipe Settings

      - RECIPE_PUBLIC='true'
      - RECIPE_SHOW_NUTRITION='true'
      - RECIPE_SHOW_ASSETS='true'
      - RECIPE_LANDSCAPE_VIEW='true'
      - RECIPE_DISABLE_COMMENTS='false'
      - RECIPE_DISABLE_AMOUNT='false'

    labels:
      - joyride.host.name=${MEALIE_CONTAINER_NAME:-mealie}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.mealie.entrypoints=websecure
      - traefik.http.routers.mealie.rule=Host(`${MEALIE_CONTAINER_NAME:-mealie}.${HOST_DOMAIN}`)
      - traefik.http.services.mealie.loadbalancer.server.port=8096
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

      # Flame dashboard labels

      - flame.type=application # "app" works too
      - flame.name=${MEALIE_FLAME_NAME:-mealie}
      - flame.url=https://${MEALIE_CONTAINER_NAME:-mealie}.${HOST_DOMAIN}
      - flame.icon=${MEALIE_FLAME_ICON:-docker} # optional, default is "docker"