version: "3"
networks:
  default:
    name: traefik
  loki:
    name: loki

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    volumes:
      - ./etc/loki:/etc/loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=false

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: unless-stopped
    volumes:
      - /var/log:/var/log
      - ./etc/promtail:/etc/promtail
    # ports:
    #   - 1514:1514 # this is only needed if you are going to send syslogs
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=false

  