version: '3'

networks:
  default:
    name: traefik

# https://hub.docker.com/_/microsoft-mssql-server    
# https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-overview?view=sql-server-ver16

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    # image: mcr.microsoft.com/mssql/server:2019-latest
    # image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql
    restart: unless-stopped
    volumes:
      - ./etc/mssql/db:/var/opt/mssql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
    labels:
      - joyride.host.name=mssql.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.mssql.entrypoints=websecure
      - traefik.http.routers.mssql.rule=Host(`mssql.${HOST_DOMAIN}`)
      - traefik.http.services.mssql.loadbalancer.server.port=1433
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true