version: '3'

networks:
  default:
    name: traefik

# https://hub.docker.com/_/microsoft-mssql-server    
# https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-overview?view=sql-server-ver16

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    # image: mcr.microsoft.com/mssql/server:2019-latest
    # image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql
    restart: unless-stopped
    volumes:
      #- ./media/databases/mssql:/var/opt/mssql # paths will have to be researched futher
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - 1433:1433
    labels:
      - joyride.host.name=mssql.${HOST_DOMAIN}
      - traefik.enable=false
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true