version: '3'

networks:
  default:
    name: traefik

volumes:
  sonarr-nfs-media:
    name: sonarr-nfs-media
    labels:
      - remove_volume_on=down
    driver_opts:
      type: nfs
      o: "addr=${SONARR_MEDIA_NFS_SERVER},nolock,noatime,soft,rw"
      device: ":${SONARR_MEDIA_NFS_SERVER_PATH}"

# https://hub.docker.com/r/linuxserver/sonarr

services:
  nfs-sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    volumes:
      - ${SONARR_CONFIG_DIR:-./etc/sonarr}:/config
      - ${SONARR_DOWNLOAD_VOLUME:-./media/downloads}:/downloads
      - ${SONARR_MEDIA_NFS_VOLUME:-sonarr-nfs-media}:/tv
      - /dev/rtc:/dev/rtc:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment: 
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000} 
      - TZ=${TZ}
    healthcheck:
      test: curl --fail http://localhost:8989 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    labels:
      - joyride.host.name=sonarr.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.sonarr.entrypoints=websecure
      - traefik.http.routers.sonarr.rule=Host(`sonarr.${HOST_DOMAIN}`)
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true