version: '3'

networks:
  default:
    name: traefik

volumes:
  radarr-nfs-media:
    name: radarr-nfs-media
    labels:
      - remove_volume_on=down
    driver_opts:
      type: nfs
      o: "addr=${RADARR_MEDIA_NFS_SERVER},nolock,noatime,soft,rw"
      device: ":${RADARR_MEDIA_NFS_SERVER_PATH}"

# https://hub.docker.com/r/linuxserver/radarr

services:
  nfs-radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    volumes:
      - ${RADARR_CONFIG_DIR:-./etc/radarr}:/config
      - ${RADARR_DOWNLOAD_VOLUME:-./media/downloads}:/downloads
      - ${RADARR_MEDIA_NFS_VOLUME:-radarr-nfs-media}:/movies
      - /dev/rtc:/dev/rtc:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment: 
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    healthcheck:
      test: curl --fail http://localhost:7878 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    labels:
      - joyride.host.name=radarr.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.radarr.entrypoints=websecure
      - traefik.http.routers.radarr.rule=Host(`radarr.${HOST_DOMAIN}`)
      - traefik.http.services.radarr.loadbalancer.server.port=7878
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true