version: '3'

networks:
  default:
    name: traefik

volumes:
  qdirstat-nfs-volume:
    name: qdirstat-nfs-volume
    labels:
      - traefik-repo-volume-type=nfs
    driver_opts:
      type: nfs
      o: "addr=${QDIRSTAT_NFS_SERVER},nolock,noatime,soft,rw"
      device: ":${QDIRSTAT_NFS_SERVER_PATH}"
    
# https://github.com/jlesage/docker-qdirstat

services:
  nfs-qdirstat:
    image: jlesage/qdirstat
    container_name: qdirstat
    restart: unless-stopped
    cap_add:
      - SYS_NICE
    environment:
      - USER_ID=${PUID:-1000}
      - GROUP_ID=${PGID:-1000}
      - TZ=${TZ}
      - KEEP_APP_RUNNING=1
      - APP_NICENESS=10
    volumes:
      - ./etc/qdirstat:/config 
      - ${QDIRSTAT_NFS_VOLUME:-qdirstat-nfs-volume}:/storage
    labels:
      - joyride.host.name=qdirstat.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.qdirstat.entrypoints=websecure
      - traefik.http.routers.qdirstat.rule=Host(`qdirstat.${HOST_DOMAIN}`)
      - traefik.http.services.qdirstat.loadbalancer.server.port=5800
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true