version: '3'

networks:
  default:
    name: traefik
    
# https://github.com/owncast/owncast

services:
  owncast:
    image: owncast/owncast:${OWNCAST_DOCKER_TAG:-latest}
    container_name: ${OWNCAST_CONTAINER_NAME:-owncast} 
    restart: ${OWNCAST_RESTART:-unless-stopped}
    volumes:
      - ./etc/owncast:/app/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports: 
      - 1935:1935
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=${OWNCAST_CONTAINER_NAME:-owncast}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.owncast.entrypoints=websecure
      - traefik.http.routers.owncast.rule=Host(`${OWNCAST_CONTAINER_NAME:-owncast}.${HOST_DOMAIN}`)
      #- traefik.http.services.owncast.loadbalancer.server.scheme=https # enable if the service wants to connect over https
      - traefik.http.services.owncast.loadbalancer.server.port=8080
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${OWNCAST_FLAME_NAME:-owncast} 
      - flame.url=https://${OWNCAST_CONTAINER_NAME:-owncast}.${HOST_DOMAIN}
      - flame.icon=${OWNCAST_FLAME_ICON:-docker} # optional, default is "docker"