version: '3'

networks:
  default:
    name: traefik
    
# <================= add links to documentation here =================>

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    volumes:
      #- ./etc/pgadmin:/var/lib/pgadmin 
      - /etc/pgadmin/servers.json:/pgadmin4/servers.json
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      # - PUID=${PUID:-1000}
      # - PGID=${PGID:-1000}
      - TZ=${TZ}
      - PGADMIN_DEFAULT_EMAIL=${CF_API_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASSWORD}
      - PGADMIN_DEFAULR_SEVER=
    labels:
      - joyride.host.name=pgadmin.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.pgadmin.entrypoints=websecure
      - traefik.http.routers.pgadmin.rule=Host(`pgadmin.${HOST_DOMAIN}`)
      - traefik.http.services.pgadmin.loadbalancer.server.port=80
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true