version: '3'

networks:
  default:
    name: traefik
    
# https://github.com/plexinc/pms-docker
# https://www.plex.tv/claim

services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    restart: unless-stopped
    # uncomment if you have intel quick sync on your cpu
    # device:
    #   - /dev/dri:/dev/dri
    volumes:
      - ${PLEX_CONFIG_DIR:-./etc/plex}:/config
      - ${PLEX_MEDIA_DIR:-./media}:${PLEX_CONTAINER_MEDIA_DIR:-/data}
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      # - 32400:32400/tcp
      # - 32400:32400/udp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=${TZ}
      - ADVERTISE_IP=https://plex.${HOST_DOMAIN}
      - ALLOWED_NETWORKS=${HOSTIP}/24
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PLEX_UID=${PUID:-1000}
      - PLEX_GID=${PGID:-1000}
      - VERSION=docker
    labels:
      - joyride.host.name=plex.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.plex.entrypoints=websecure
      - traefik.http.routers.plex.rule=Host(`plex.${HOST_DOMAIN}`)
      - traefik.http.services.plex.loadbalancer.server.port=32400
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true
