version: '3'

networks:
  default:
    name: traefik

# https://hub.docker.com/r/linuxserver/pwndrop

services:
  pwndrop:
    image: lscr.io/linuxserver/pwndrop:latest
    container_name: pwndrop
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - SECRET_PATH=/pwndrop #optional
    volumes:
      - ./etc/pwndrop:/config
    # ports:
    #   - 8080:8080
    labels:
      - joyride.host.name=pwndrop.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.pwndrop.rule=Host(`pwndrop.${HOST_DOMAIN}`)
      - traefik.http.routers.pwndrop.entrypoints=websecure
      - traefik.http.services.pwndrop.loadbalancer.server.port=8080
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true