version: '3'

networks:
  default:
    name: traefik

# https://hub.docker.com/r/linuxserver/radarr

services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    volumes:
      - ${RADARR_CONFIG_DIR:-./etc/radarr}:/config
      - ${MEDIA_MOVIES_DIR:-./media/movies}:/movies
      - ${MEDIA_DOWNLOADS_DIR:-./media/downloads}:/downloads
      - /dev/rtc:/dev/rtc:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment: 
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    healthcheck:
      test: curl --fail http://localhost:7878 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    labels:
      - joyride.host.name=radarr.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.radarr.entrypoints=websecure
      - traefik.http.routers.radarr.rule=Host(`radarr.${HOST_DOMAIN}`)
      - traefik.http.services.radarr.loadbalancer.server.port=7878
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true