version: '3'

networks:
  default:
    name: traefik

# https://hub.docker.com/r/linuxserver/radarr

services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    volumes:
      - ./etc/radarr:/config
      - ./media/movies:/movies
      - ./media/downloads:/downloads
      - /dev/rtc:/dev/rtc:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment: 
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=radarr.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.radarr.entrypoints=websecure
      - traefik.http.routers.radarr.rule=Host(`radarr.${HOST_DOMAIN}`)
      - traefik.http.services.radarr.loadbalancer.server.scheme=http
      - traefik.http.services.radarr.loadbalancer.server.port=7878