version: '3'

networks:
  default:
    name: traefik
    
# <================= add links to documentation here =================>

services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:${RECYCLARR_DOCKER_TAG:-latest}
    container_name: ${RECYCLARR_CONTAINER_NAME:-recyclarr} 
    restart: unless-stopped
    volumes:
      - ./etc/recyclarr:/config # <==== this probably needs changed 
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - traefik.enable=false
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true