version: '3'

networks:
  default:
    name: traefik
    
# https://hub.docker.com/r/recyclarr/recyclarr
# https://recyclarr.dev/wiki/installation/

services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:${RECYCLARR_DOCKER_TAG:-latest}
    container_name: ${RECYCLARR_CONTAINER_NAME:-recyclarr} 
    restart: unless-stopped
    volumes:
      - ./etc/recyclarr:/config 
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - traefik.enable=false
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true