version: '3'

networks:
  default:
    name: traefik
    
# <================= add links to documentation here =================>

services:
  redis:
    image: <==== container_image ====>
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./etc/redis:/config # <==== this probably needs changed ====>
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      #- joyride.host.name=redis.${HOST_DOMAIN}
      # - traefik.enable=true
      # - traefik.http.routers.redis.entrypoints=websecure
      # - traefik.http.routers.redis.rule=Host(`redis.${HOST_DOMAIN}`)
      # - traefik.http.services.redis.loadbalancer.server.port=8096
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true