version: '3'

networks:
  default:
    name: sftp-server

# https://github.com/drakkan/sftpgo

services:
  sftp-server:
    image: drakkan/sftpgo:${SFTPGO_DOCKER_TAG:-latest}
    container_name: sftp-server
    restart: unless-stopped  
    ports:
      - 7222:2022
      - 7272:8080
    volumes:
      - ./etc/sftp-server:/var/lib/sftpgo
      - ${SFTP_DATA_VOLUME:-./media}:/srv/sftpgo
