version: '3'

networks:
  default:
    name: traefik

# https://hub.docker.com/r/linuxserver/snapdrop

services:
  snapdrop:
    image: lscr.io/linuxserver/snapdrop:latest
    container_name: snapdrop
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    volumes:
      - ./etc/snapdrop:/config
    # ports:
    #   - 80:80
    #   - 443:443
    labels:
      - joyride.host.name=snapdrop.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.snapdrop.rule=Host(`snapdrop.${HOST_DOMAIN}`)
      - traefik.http.routers.snapdrop.entrypoints=websecure
      - traefik.http.services.snapdrop.loadbalancer.server.port=80
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true