version: '3'

networks:
  default:
    name: traefik

# https://hub.docker.com/r/linuxserver/sonarr

services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    volumes:
      - ./etc/sonarr:/config
      - ${MEDIA_SHOWS_DIR:-./media/shows}:/tv
      - ${MEDIA_DOWNLOADS_DIR:-./media/downloads}:/downloads
      - /dev/rtc:/dev/rtc:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment: 
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000} 
      - TZ=${TZ}
    healthcheck:
      test: curl --fail http://localhost:8989 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    labels:
      - joyride.host.name=sonarr.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.sonarr.entrypoints=websecure
      - traefik.http.routers.sonarr.rule=Host(`sonarr.${HOST_DOMAIN}`)
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true