version: '3'

networks:
  default:
    name: traefik

services:
  syncthing:
    image: linuxserver/syncthing:latest
    container_name: syncthing
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - UMASK=022
    volumes:
      - ./etc/syncthing:/config
      - ./media/sync:/sync
    ports:
      #- 8384:8384
      - 22000:22000
      - 21027:21027/udp
    labels:
      - joyride.host.name=sync.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.sync.entrypoints=websecure
      - traefik.http.routers.sync.rule=Host(`sync.${HOST_DOMAIN}`)
      - traefik.http.services.sync.loadbalancer.server.port=8384
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true