version: '3'

networks:
  default:
    name: traefik

# https://github.com/dani-garcia/vaultwarden

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - ./etc/vaultwarden:/data
      - /dev/rtc:/dev/rtc:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment: 
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=vaultwarden.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.vaultwarden.entrypoints=websecure
      - traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.${HOST_DOMAIN}`)
      - traefik.http.services.vaultwarden.loadbalancer.server.port=80
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true