version: '3'

networks:
  default:
    name: traefik
    
# https://github.com/aceberg/WatchYourLAN

services:
  watchyourlan:
    image: aceberg/watchyourlan:${WATCHYOURLAN_DOCKER_TAG:-latest}
    container_name: ${WATCHYOURLAN_CONTAINER_NAME:-watchyourlan} 
    restart: ${WATCHYOURLAN_RESTART:-unless-stopped}
    network_mode: host
    volumes:
      - ./etc/watchyourlan:/data 
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - IFACE=${WATCHYOURLAN_IFACE:-eth0}
      - GUIIP=${WATCHYOURLAN_GUIIP:-0.0.0.0}
      - THEME=${WATCHYOURLAN_THEME:-darkly}
      - TIMEOUT=${WATCHYOURLAN_TIMEOUT:-600}
      - SHOUTRRR_URL=${WATCHYOURLAN_SHOUTRRR_URL}
    labels:
      - joyride.host.name=${WATCHYOURLAN_CONTAINER_NAME:-watchyourlan}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.watchyourlan.entrypoints=websecure
      - traefik.http.routers.watchyourlan.rule=Host(`${WATCHYOURLAN_CONTAINER_NAME:-watchyourlan}.${HOST_DOMAIN}`)
      - traefik.http.services.watchyourlan.loadbalancer.server.port=8840
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${WATCHYOURLAN_FLAME_NAME:-watchyourlan} 
      - flame.url=${WATCHYOURLAN_CONTAINER_NAME:-watchyourlan}.${HOST_DOMAIN}
      - flame.icon=${WATCHYOURLAN_FLAME_ICON:-docker} # optional, default is "docker"