version: '3'

networks:
  default:
    name: traefik
    
# https://github.com/SECUREFOREST/WebMap

services:
  webmap:
    image: secureforest/webmap
    container_name: webmap
    restart: unless-stopped
    volumes:
      - ./etc/webmap:/opt/xml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=webmap.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.webmap.entrypoints=websecure
      - traefik.http.routers.webmap.rule=Host(`webmap.${HOST_DOMAIN}`)
      - traefik.http.services.webmap.loadbalancer.server.port=8000
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true