version: '3'

networks:
  default:
    name: traefik
    
# <================= add links to documentation here =================>

services:
  wikijs:
    image: <==== container_image ====>:${WIKIJS_DOCKER_TAG:-latest}
    container_name: ${WIKIJS_CONTAINER_NAME:-wikijs} 
    restart: unless-stopped
    volumes:
      - ./etc/wikijs:/config # <==== this probably needs changed 
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=${WIKIJS_CONTAINER_NAME:-wikijs}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.wikijs.entrypoints=websecure
      - traefik.http.routers.wikijs.rule=Host(`${WIKIJS_CONTAINER_NAME:-wikijs}.${HOST_DOMAIN}`)
      - traefik.http.services.wikijs.loadbalancer.server.port=8096
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${WIKIJS_FLAME_NAME:-wikijs} 
      - flame.url=${WIKIJS_CONTAINER_NAME:-wikijs}.${HOST_DOMAIN}
      - flame.icon=${WIKIJS_FLAME_ICON:-docker} # optional, default is "docker"

