version: '3'

networks:
  default:
    name: traefik


services:
  yacht:
    image: selfhostedpro/yacht
    container_name: yacht
    volumes:
      - ./etc/yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: 
      - .env
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.yacht.entrypoints=websecure"
      - "traefik.http.routers.yacht.rule=Host(`yacht.${HOST_DOMAIN}`)"
      - "traefik.http.routers.yacht.tls=true"
      - "traefik.http.routers.yacht.service=yacht"
      - "traefik.http.services.yacht.loadbalancer.server.port=8000"
