version: '3'

networks:
  default:
    name: traefik

# https://github.com/SelfhostedPro/Yacht

services:
  yacht:
    image: selfhostedpro/yacht:${YACHT_DOCKER_TAG:-latest}
    container_name: yacht
    restart: unless-stopped
    volumes:
      - ./etc/yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: 
      - .env
    labels:
      - joyride.host.name=yacht.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.yacht.entrypoints=websecure
      - traefik.http.routers.yacht.rule=Host(`yacht.${HOST_DOMAIN}`)
      - traefik.http.routers.yacht.tls=true
      - traefik.http.routers.yacht.service=yacht
      - traefik.http.services.yacht.loadbalancer.server.port=8000


      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${YACHT_FLAME_NAME:-yacht} 
      - flame.url=https://${YACHT_CONTAINER_NAME:-yacht}.${HOST_DOMAIN}
      - flame.icon=${YACHT_FLAME_ICON:-docker} # optional, default is "docker"