- hosts: localhost
  become: true
  tasks:
    - name: install dependencies
      become: yes
      apt:
        update_cache: yes
        name:
          - nvidia-driver-535 
          - nvidia-dkms-535
        state: present

  roles:
    - nvidia.nvidia_docker
  #   - nvidia.nvidia_driver
  #   