- hosts: localhost
  become: true
  tasks:
    - name: install libnvidia-decode
      package:
        name: libnvidia-decode-515-server
        state: present
  roles:
    - nvidia.nvidia_driver
    - nvidia.nvidia_docker