# Remember to add the host name to the opnsense admin page so that you wont get a DNS rebind error
# See https://github.com/traefikturkey/guides/blob/master/opnsense-configuration-traefik.md for tips 

http:
 #region routers 
  routers:
    opnsense:
      entryPoints:
        - "websecure"
      rule: "Host(`{{env "OPNSENSE_HOST_NAME"}}.{{env "HOST_DOMAIN"}}`)"
      middlewares:
        - default-headers
      tls: {}
      service: opnsense

  services:
    opnsense:
      loadBalancer:
        servers:
          - url: "https://{{env "OPNSENSE_ADDRESS"}}"
        passHostHeader: true
