http:
  routers:

    pihole:
      entryPoints:
        - websecure
      rule: "Host(`{{env "PIHOLE_HOST_NAME"}}.{{env "HOST_DOMAIN"}}`)"
      middlewares:
        - default-headers
        - addprefix-pihole
      tls: {}
      service: pihole

  services:
    pihole:
      loadBalancer:
        servers:
          - url: "http://{{env "PIHOLE_ADDRESS"}}:80"
        passHostHeader: true

  middlewares:
    addprefix-pihole:
      addPrefix:
        prefix: "/admin"
