http:
 #region routers 
  routers:
    proxmox:
      entryPoints:
        - "websecure"
      rule: "Host(`{{env "PROXMOX_HOST_NAME"}}.{{env "HOST_DOMAIN"}}`)"
      middlewares:
        - default-headers
      tls: {}
      service: proxmox

  services:
    proxmox:
      loadBalancer:
        servers:
          - url: "https://{{env "PROXMOX_ADDRESS"}}:8006/"
        passHostHeader: true