http:
 #region routers 
  routers:
    rancher:
      entryPoints:
        - "websecure"
      rule: "Host(`{{env "RANCHER_HOST_NAME"}}.{{env "HOST_DOMAIN"}}`)"
      middlewares:
        - default-headers
      tls: {}
      service: rancher

  services:
    rancher:
      loadBalancer:
        servers:
          - url: "https://{{env "RANCHER_ADDRESS"}}"
        passHostHeader: true