name: Generate Services Markdown

on:
  push:
    paths:
      - 'services-available/**/*.yml'
      - '.github/workflows/generate-services-markdown.yml'
      - '.github/scripts/generate-services-markdown.yml'

jobs:

  generate-services-markdown:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Services Markdown
        run: |
          chmod +x .github/scripts/generate-services-markdown.sh
          ls -lha .github/scripts
          pwd
          echo "Running generate-services-markdown.sh"
          
          ./github/scripts/generate-services-markdown.sh